---
apiVersion: v1
kind: Pod
metadata:
    name: hello-pod
spec:
    containers:
      - image: qualitythought/gameoflife:07112020
        name: gameoflife
        ports:
          - containerPort: 8080
            protocol: TCP
