---
apiVersion: v1
kind: Pod
metadata:
    name: first-pod
spec:
    containers:
      - image: qualitythought/gameoflife:07112020
        name: my-gol
        ports:
          - containerPort: 8080
            protocol: TCP
