---
apiVersion: v1
kind: Pod
metadata:
    name: hellopod
spec:
    containers:
      - image: springcommunity/spring-petclinic-vets-service:java11
        name: gol
        ports:
          - containerPort: 8080
            protocol: TCP
