---
apiVersion: v1
kind: Pod
metadata:
    name: hellopod
spec:
    containers:
      - image: qualitythought/gameoflife:07112020
        name: gol
        ports:
          - containerPort: 8080
            protocol: TCP
