---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: jenkins
spec:
    minReadySeconds: 5
    replicas: 6
    selector:
        matchLabels:
            app: jenkins
            version: "2.60.3"
    template:
        metadata:
            labels:
                app: jenkins
                version: "2.60.3"
        spec:
            containers:
              - image: jenkins:2.60.3
                name: jenkins
                ports:
                  - containerPort: 8080
                    protocol: TCP

