---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: gol-rs
spec:
    minReadySeconds: 5
    replicas : 3
    selector:
        matchExpressions:
          - key: gol
    template:
        metadata:
            name: gol
            labels:
                app: gol
                version: 1.0      
        spec:
            containers:
              - image: qualitythought/gameoflife:07112020
                name: gol
                ports:
                  - containerPort: 8080
                    name: Port8080
                    protocol: TCP